// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BiblioContext))]
    [Migration("20250901194821_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Isabel Allende"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Mario Vargas Llosa"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Jorge Luis Borges"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Nombre = "Pablo Neruda"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Nombre = "Julio Cortázar"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Nombre = "Laura Esquivel"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Nombre = "Carlos Fuentes"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Nombre = "Miguel de Cervantes"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Nombre = "Federico García Lorca"
                        });
                });

            modelBuilder.Entity("Service.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Ingeniería en Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Medicina"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Derecho"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Arquitectura"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Nombre = "Psicología"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Nombre = "Administración de Empresas"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Nombre = "Contabilidad"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Nombre = "Comunicación Social"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Nombre = "Educación"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Nombre = "Ingeniería Civil"
                        });
                });

            modelBuilder.Entity("Service.Models.Editorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Editoriales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Penguin Random House"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "HarperCollins"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Simon & Schuster"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Hachette Livre"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Nombre = "Macmillan Publishers"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Nombre = "Scholastic"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Nombre = "Bloomsbury"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Nombre = "Oxford University Press"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Nombre = "Cambridge University Press"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Nombre = "Wiley"
                        });
                });

            modelBuilder.Entity("Service.Models.Ejemplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.ToTable("Ejemplares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disponible = true,
                            Estado = 1,
                            IsDeleted = false,
                            LibroId = 1
                        },
                        new
                        {
                            Id = 2,
                            Disponible = false,
                            Estado = 2,
                            IsDeleted = false,
                            LibroId = 1
                        },
                        new
                        {
                            Id = 3,
                            Disponible = true,
                            Estado = 4,
                            IsDeleted = false,
                            LibroId = 2
                        },
                        new
                        {
                            Id = 4,
                            Disponible = false,
                            Estado = 3,
                            IsDeleted = false,
                            LibroId = 2
                        },
                        new
                        {
                            Id = 5,
                            Disponible = true,
                            Estado = 0,
                            IsDeleted = false,
                            LibroId = 3
                        },
                        new
                        {
                            Id = 6,
                            Disponible = false,
                            Estado = 1,
                            IsDeleted = false,
                            LibroId = 4
                        },
                        new
                        {
                            Id = 7,
                            Disponible = true,
                            Estado = 2,
                            IsDeleted = false,
                            LibroId = 5
                        },
                        new
                        {
                            Id = 8,
                            Disponible = false,
                            Estado = 4,
                            IsDeleted = false,
                            LibroId = 6
                        },
                        new
                        {
                            Id = 9,
                            Disponible = true,
                            Estado = 3,
                            IsDeleted = false,
                            LibroId = 7
                        },
                        new
                        {
                            Id = 10,
                            Disponible = false,
                            Estado = 0,
                            IsDeleted = false,
                            LibroId = 8
                        });
                });

            modelBuilder.Entity("Service.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Novela"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Poesía"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Cuento"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Ensayo"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Nombre = "Teatro"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Nombre = "Fantasía"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Nombre = "Ciencia Ficción"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Nombre = "Misterio"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Nombre = "Romance"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Nombre = "Aventura"
                        });
                });

            modelBuilder.Entity("Service.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EditorialId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Paginas")
                        .HasColumnType("int");

                    b.Property<string>("Portada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EditorialId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnioPublicacion = 1967,
                            Descripcion = "Novela emblemática del realismo mágico.",
                            EditorialId = 1,
                            IsDeleted = false,
                            Paginas = 417,
                            Portada = "https://example.com/cien_anos_de_soledad.jpg",
                            Sinopsis = "La historia de la familia Buendía a lo largo de varias generaciones en el pueblo ficticio de Macondo.",
                            Titulo = "Cien Años de Soledad"
                        },
                        new
                        {
                            Id = 2,
                            AnioPublicacion = 1982,
                            Descripcion = "Novela que mezcla lo real con lo sobrenatural.",
                            EditorialId = 2,
                            IsDeleted = false,
                            Paginas = 448,
                            Portada = "https://example.com/la_casa_de_los_espiritus.jpg",
                            Sinopsis = "Relata la saga de la familia Trueba, explorando temas de amor, política y destino.",
                            Titulo = "La Casa de los Espíritus"
                        },
                        new
                        {
                            Id = 3,
                            AnioPublicacion = 1963,
                            Descripcion = "Novela que critica la sociedad peruana.",
                            EditorialId = 3,
                            IsDeleted = false,
                            Paginas = 320,
                            Portada = "https://example.com/la_ciudad_y_los_perros.jpg",
                            Sinopsis = "Ambientada en un colegio militar, aborda temas de violencia, poder y corrupción.",
                            Titulo = "La Ciudad y los Perros"
                        },
                        new
                        {
                            Id = 4,
                            AnioPublicacion = 1944,
                            Descripcion = "Colección de cuentos filosóficos y metafísicos.",
                            EditorialId = 4,
                            IsDeleted = false,
                            Paginas = 224,
                            Portada = "https://example.com/ficciones.jpg",
                            Sinopsis = "Una serie de relatos que exploran conceptos como el infinito, los laberintos y la realidad.",
                            Titulo = "Ficciones"
                        },
                        new
                        {
                            Id = 5,
                            AnioPublicacion = 1924,
                            Descripcion = "Antología de poesía romántica.",
                            EditorialId = 5,
                            IsDeleted = false,
                            Paginas = 100,
                            Portada = "https://example.com/veinte_poemas_de_amor.jpg",
                            Sinopsis = "Una colección de poemas que expresan el amor y la pasión con una intensidad única.",
                            Titulo = "Veinte Poemas de Amor y una Canción Desesperada"
                        },
                        new
                        {
                            Id = 6,
                            AnioPublicacion = 1963,
                            Descripcion = "Novela experimental y vanguardista.",
                            EditorialId = 6,
                            IsDeleted = false,
                            Paginas = 576,
                            Portada = "https://example.com/rayuela.jpg",
                            Sinopsis = "La historia de Horacio Oliveira y su búsqueda de sentido en la vida a través de una estructura narrativa no lineal.",
                            Titulo = "Rayuela"
                        },
                        new
                        {
                            Id = 7,
                            AnioPublicacion = 1989,
                            Descripcion = "Novela que combina romance y realismo mágico.",
                            EditorialId = 7,
                            IsDeleted = false,
                            Paginas = 256,
                            Portada = "https://example.com/como_agua_para_chocolate.jpg",
                            Sinopsis = "La historia de Tita, una joven cuya vida está marcada por las tradiciones familiares y su amor prohibido.",
                            Titulo = "Como Agua para Chocolate"
                        },
                        new
                        {
                            Id = 8,
                            AnioPublicacion = 1929,
                            Descripcion = "Novela política y social.",
                            EditorialId = 8,
                            IsDeleted = false,
                            Paginas = 300,
                            Portada = "https://example.com/la_sombra_del_caudillo.jpg",
                            Sinopsis = "Una crítica a la dictadura y la corrupción en México a través de la historia de un líder militar.",
                            Titulo = "La Sombra del Caudillo"
                        },
                        new
                        {
                            Id = 9,
                            AnioPublicacion = 1605,
                            Descripcion = "Clásico de la literatura española.",
                            EditorialId = 9,
                            IsDeleted = false,
                            Paginas = 863,
                            Portada = "https://example.com/don_quijote.jpg",
                            Sinopsis = "Las aventuras del ingenioso hidalgo Don Quijote y su fiel escudero Sancho Panza en su lucha contra la injusticia.",
                            Titulo = "Don Quijote de la Mancha"
                        },
                        new
                        {
                            Id = 10,
                            AnioPublicacion = 1933,
                            Descripcion = "Tragedia teatral basada en hechos reales.",
                            EditorialId = 10,
                            IsDeleted = false,
                            Paginas = 80,
                            Portada = "https://example.com/bodas_de_sangre.jpg",
                            Sinopsis = "La historia de un amor imposible que termina en tragedia, explorando temas de pasión, destino y honor.",
                            Titulo = "Bodas de Sangre"
                        });
                });

            modelBuilder.Entity("Service.Models.LibroAutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("LibroId");

                    b.ToTable("LibroAutores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorId = 1,
                            IsDeleted = false,
                            LibroId = 1
                        },
                        new
                        {
                            Id = 2,
                            AutorId = 2,
                            IsDeleted = false,
                            LibroId = 2
                        },
                        new
                        {
                            Id = 3,
                            AutorId = 3,
                            IsDeleted = false,
                            LibroId = 3
                        },
                        new
                        {
                            Id = 4,
                            AutorId = 4,
                            IsDeleted = false,
                            LibroId = 4
                        },
                        new
                        {
                            Id = 5,
                            AutorId = 5,
                            IsDeleted = false,
                            LibroId = 5
                        },
                        new
                        {
                            Id = 6,
                            AutorId = 6,
                            IsDeleted = false,
                            LibroId = 6
                        },
                        new
                        {
                            Id = 7,
                            AutorId = 7,
                            IsDeleted = false,
                            LibroId = 7
                        },
                        new
                        {
                            Id = 8,
                            AutorId = 8,
                            IsDeleted = false,
                            LibroId = 8
                        },
                        new
                        {
                            Id = 9,
                            AutorId = 9,
                            IsDeleted = false,
                            LibroId = 9
                        },
                        new
                        {
                            Id = 10,
                            AutorId = 10,
                            IsDeleted = false,
                            LibroId = 10
                        });
                });

            modelBuilder.Entity("Service.Models.LibroGenero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("LibroId");

                    b.ToTable("LibroGeneros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GeneroId = 1,
                            IsDeleted = false,
                            LibroId = 1
                        },
                        new
                        {
                            Id = 2,
                            GeneroId = 1,
                            IsDeleted = false,
                            LibroId = 2
                        },
                        new
                        {
                            Id = 3,
                            GeneroId = 4,
                            IsDeleted = false,
                            LibroId = 3
                        },
                        new
                        {
                            Id = 4,
                            GeneroId = 3,
                            IsDeleted = false,
                            LibroId = 4
                        },
                        new
                        {
                            Id = 5,
                            GeneroId = 2,
                            IsDeleted = false,
                            LibroId = 5
                        },
                        new
                        {
                            Id = 6,
                            GeneroId = 6,
                            IsDeleted = false,
                            LibroId = 6
                        },
                        new
                        {
                            Id = 7,
                            GeneroId = 1,
                            IsDeleted = false,
                            LibroId = 7
                        },
                        new
                        {
                            Id = 8,
                            GeneroId = 4,
                            IsDeleted = false,
                            LibroId = 8
                        },
                        new
                        {
                            Id = 9,
                            GeneroId = 1,
                            IsDeleted = false,
                            LibroId = 9
                        },
                        new
                        {
                            Id = 10,
                            GeneroId = 5,
                            IsDeleted = false,
                            LibroId = 10
                        });
                });

            modelBuilder.Entity("Service.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EjemplarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EjemplarId = 1,
                            FechaDevolucion = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            EjemplarId = 2,
                            FechaDevolucion = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            EjemplarId = 3,
                            FechaDevolucion = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            EjemplarId = 4,
                            FechaDevolucion = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            EjemplarId = 5,
                            FechaDevolucion = new DateTime(2023, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 6,
                            EjemplarId = 6,
                            FechaDevolucion = new DateTime(2023, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 7,
                            EjemplarId = 7,
                            FechaDevolucion = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 8,
                            EjemplarId = 8,
                            FechaDevolucion = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 9,
                            EjemplarId = 9,
                            FechaDevolucion = new DateTime(2023, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 9
                        },
                        new
                        {
                            Id = 10,
                            EjemplarId = 10,
                            FechaDevolucion = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UsuarioId = 10
                        });
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistracion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoRol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dni = "12345678",
                            Domicilio = "Calle Falsa 123",
                            Email = "juan.perez@email.com",
                            FechaRegistracion = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Juan Pérez",
                            Observacion = "",
                            Password = "123456",
                            Telefono = "1112345678",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 2,
                            Dni = "23456789",
                            Domicilio = "Av. Siempre Viva 742",
                            Email = "maria.gomez@email.com",
                            FechaRegistracion = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "María Gómez",
                            Observacion = "",
                            Password = "abcdef",
                            Telefono = "1123456789",
                            TipoRol = 2
                        },
                        new
                        {
                            Id = 3,
                            Dni = "34567890",
                            Domicilio = "Calle 9 de Julio 456",
                            Email = "carlos.lopez@email.com",
                            FechaRegistracion = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Carlos López",
                            Observacion = "",
                            Password = "qwerty",
                            Telefono = "1134567890",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 4,
                            Dni = "45678901",
                            Domicilio = "Av. Corrientes 1000",
                            Email = "ana.torres@email.com",
                            FechaRegistracion = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Ana Torres",
                            Observacion = "",
                            Password = "password",
                            Telefono = "1145678901",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 5,
                            Dni = "56789012",
                            Domicilio = "Calle Mitre 321",
                            Email = "pedro.sanchez@email.com",
                            FechaRegistracion = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Pedro Sánchez",
                            Observacion = "",
                            Password = "pedro123",
                            Telefono = "1156789012",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 6,
                            Dni = "67890123",
                            Domicilio = "Av. Belgrano 654",
                            Email = "lucia.fernandez@email.com",
                            FechaRegistracion = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Lucía Fernández",
                            Observacion = "",
                            Password = "lucia456",
                            Telefono = "1167890123",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 7,
                            Dni = "78901234",
                            Domicilio = "Calle San Martín 987",
                            Email = "miguel.ramirez@email.com",
                            FechaRegistracion = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Miguel Ramírez",
                            Observacion = "",
                            Password = "miguel789",
                            Telefono = "1178901234",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 8,
                            Dni = "89012345",
                            Domicilio = "Av. Rivadavia 1111",
                            Email = "sofia.herrera@email.com",
                            FechaRegistracion = new DateTime(2023, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Sofía Herrera",
                            Observacion = "",
                            Password = "sofia321",
                            Telefono = "1189012345",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 9,
                            Dni = "90123456",
                            Domicilio = "Calle Moreno 222",
                            Email = "diego.castro@email.com",
                            FechaRegistracion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Diego Castro",
                            Observacion = "",
                            Password = "diego654",
                            Telefono = "1190123456",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 10,
                            Dni = "01234567",
                            Domicilio = "Av. Santa Fe 333",
                            Email = "valentina.ruiz@email.com",
                            FechaRegistracion = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Valentina Ruiz",
                            Observacion = "",
                            Password = "valen987",
                            Telefono = "1201234567",
                            TipoRol = 0
                        });
                });

            modelBuilder.Entity("Service.Models.UsuarioCarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioCarreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarreraId = 1,
                            IsDeleted = false,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarreraId = 2,
                            IsDeleted = false,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            CarreraId = 3,
                            IsDeleted = false,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            CarreraId = 4,
                            IsDeleted = false,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            CarreraId = 5,
                            IsDeleted = false,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 6,
                            CarreraId = 6,
                            IsDeleted = false,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 7,
                            CarreraId = 7,
                            IsDeleted = false,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 8,
                            CarreraId = 8,
                            IsDeleted = false,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 9,
                            CarreraId = 9,
                            IsDeleted = false,
                            UsuarioId = 9
                        },
                        new
                        {
                            Id = 10,
                            CarreraId = 10,
                            IsDeleted = false,
                            UsuarioId = 10
                        });
                });

            modelBuilder.Entity("Service.Models.Ejemplar", b =>
                {
                    b.HasOne("Service.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Service.Models.Libro", b =>
                {
                    b.HasOne("Service.Models.Editorial", "Editorial")
                        .WithMany()
                        .HasForeignKey("EditorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editorial");
                });

            modelBuilder.Entity("Service.Models.LibroAutor", b =>
                {
                    b.HasOne("Service.Models.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Service.Models.LibroGenero", b =>
                {
                    b.HasOne("Service.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Service.Models.Prestamo", b =>
                {
                    b.HasOne("Service.Models.Ejemplar", "Ejemplar")
                        .WithMany()
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejemplar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Service.Models.UsuarioCarrera", b =>
                {
                    b.HasOne("Service.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
